# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - fauxhai-chef
  
artifact_channels:
  - workstation-build
  - stable
  - LTS-2024

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true
  - habitat/build:
      description: Build the Habitat packages for faixhai
  - habitat/test:
      definition: .expeditor/habitat-test.pipeline.yml
      trigger: default

release_branches:
  - workstation-LTS:
      version_constraint: 9.*
  - main:
      version_constraint: 9.*

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

changelog:
  rollup_header: Changes not yet released to rubygems.org

subscriptions:
  # These actions are taken, in order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
      - trigger_pipeline:habitat/build:
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"
          only_if: built_in:bump_version
      - built_in:build_gem:
          only_if: built_in:bump_version
 
# this is the only way currently to promote built-in rubygems publish
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:rollover_changelog
      - built_in:promote_habitat_packages
      - built_in:publish_rubygems

  # subscription to fire off any other promotions that you may need for an additional channnel like LTS or something. 
  - workload: staged_workload_released:{{agent_id}}:hab_unstable_promote:*
    actions:
    - bash:.expeditor/scripts/promote-hab-pkgs.sh:
        post_commit: true

staging_areas:
  - hab_unstable_promote:
      workload: hab_package_published:stable:chef/fauxhai/{{version_constraint}}  