#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates ARCHITECTURE.md with a Mermaid diagram of the Fauxhai codebase.
# Usage:
#   ruby scripts/generate_architecture_diagram.rb [output_path]
#
# The script scans lib/fauxhai/ to discover modules, classes, and their
# relationships, then writes a Markdown file containing a Mermaid diagram
# and a platform summary.

require "json"

module Fauxhai
  module ArchitectureGenerator
    LIB_ROOT = File.expand_path("../../lib/fauxhai", __FILE__)
    DEFAULT_OUTPUT = File.expand_path("../../ARCHITECTURE.md", __FILE__)

    # Describes one Ruby source file discovered under lib/fauxhai/.
    SourceFile = Struct.new(:relative_path, :basename, :requires, :classes, :modules, keyword_init: true)

    class << self
      # Main entry point. Returns the Markdown string and optionally writes it.
      def generate(output_path: DEFAULT_OUTPUT, write: true)
        source_files = scan_source_files
        platforms    = scan_platforms
        markdown     = render(source_files, platforms)

        if write
          File.write(output_path, markdown)
          $stdout.puts "ARCHITECTURE.md written to #{output_path}" unless ENV["FAUXHAI_SILENT"]
        end

        markdown
      end

      # --------------- scanning ------------------------------------------------

      def scan_source_files
        ruby_files = Dir.glob(File.join(LIB_ROOT, "**", "*.rb"))
        ruby_files.map { |path| parse_ruby_file(path) }
      end

      def parse_ruby_file(path)
        relative = path.sub("#{LIB_ROOT}/", "")
        content  = File.read(path)

        requires = content.scan(/require(?:_relative)?\s+["']([^"']+)["']/).flatten
        classes  = content.scan(/class\s+([\w:]+)/).flatten
        modules  = content.scan(/module\s+([\w:]+)/).flatten

        SourceFile.new(
          relative_path: relative,
          basename: File.basename(path, ".rb"),
          requires: requires,
          classes: classes,
          modules: modules
        )
      end

      def scan_platforms
        platforms_dir = File.join(LIB_ROOT, "platforms")
        return {} unless File.directory?(platforms_dir)

        result = {}
        Dir.children(platforms_dir).sort.each do |entry|
          full = File.join(platforms_dir, entry)
          next unless File.directory?(full)
          next if entry.start_with?(".") || entry == "chefspec" || entry == "runner"

          versions = Dir.glob(File.join(full, "*.json")).map { |f| File.basename(f, ".json") }
          result[entry] = versions.sort unless versions.empty?
        end
        result
      end

      # --------------- rendering -----------------------------------------------

      def render(source_files, platforms)
        lines = []
        lines << "# Fauxhai Architecture"
        lines << ""
        lines << "_Auto-generated by `scripts/generate_architecture_diagram.rb` — do not edit manually._"
        lines << ""
        lines << render_overview
        lines << render_mermaid_diagram(source_files)
        lines << render_module_descriptions(source_files)
        lines << render_platform_summary(platforms)
        lines << render_data_flow
        lines << render_generation_metadata
        lines.join("\n")
      end

      def render_overview
        <<~MD
          ## Overview

          Fauxhai is a Ruby gem that provides mock Ohai data for ChefSpec tests.
          It has two primary entry points:

          - **`Fauxhai.mock`** — returns simulated Ohai data from bundled JSON files
            (via `Fauxhai::Mocker`).
          - **`Fauxhai.fetch`** — SSHes into a real node and captures live Ohai data
            (via `Fauxhai::Fetcher`).

          The `bin/fauxhai` CLI uses `Fauxhai::Runner` to collect Ohai data on the
          current machine and print sanitised JSON.
        MD
      end

      def render_mermaid_diagram(source_files)
        lines = []
        lines << "## Component Diagram"
        lines << ""
        lines << "```mermaid"
        lines << "graph TD"

        # Core module
        lines << '  Fauxhai["Fauxhai (lib/fauxhai.rb)"]'

        # Discovered components
        core_files = source_files.reject { |sf| sf.relative_path.start_with?("runner/") }
        runner_files = source_files.select { |sf| sf.relative_path.start_with?("runner/") }

        core_files.each do |sf|
          id = node_id(sf)
          label = sf.classes.first || sf.modules.reject { |m| m == "Fauxhai" }.first || sf.basename.capitalize
          lines << "  #{id}[\"#{label}\"]"
        end

        runner_files.each do |sf|
          id = node_id(sf)
          label = "Runner::#{sf.basename.capitalize}"
          lines << "  #{id}[\"#{label}\"]"
        end

        # Edges — autoload / require relationships
        lines << ""
        lines << "  %% Core autoloads"
        %w[Mocker Fetcher Exception].each do |name|
          lines << "  Fauxhai --> #{name}"
        end

        # Runner relationship
        lines << "  Fauxhai --> Runner"
        runner_files.each do |sf|
          id = node_id(sf)
          lines << "  Runner --> #{id}"
        end

        # Mocker -> platforms data
        lines << ""
        lines << "  %% Data dependencies"
        lines << '  Platforms["Platform JSON files"]'
        lines << "  Mocker --> Platforms"
        lines << "  Mocker --> Exception"
        lines << "  Fetcher --> Exception"

        # External deps
        lines << ""
        lines << "  %% External dependencies"
        lines << '  NetSSH["net/ssh"]'
        lines << '  NetHTTP["net/http"]'
        lines << '  Ohai["ohai"]'
        lines << '  ChefSpec["ChefSpec (optional)"]'
        lines << "  Fetcher --> NetSSH"
        lines << "  Mocker --> NetHTTP"
        lines << "  Runner --> Ohai"
        lines << "  Fetcher -.-> ChefSpec"

        lines << "```"
        lines << ""
        lines.join("\n")
      end

      def render_module_descriptions(source_files)
        lines = []
        lines << "## Module Descriptions"
        lines << ""

        descriptions = {
          "mocker" => "`Fauxhai::Mocker` — Loads platform mock data from local JSON or GitHub. Supports version prefix matching and deprecation warnings.",
          "fetcher" => "`Fauxhai::Fetcher` — SSHes into a remote host via `net/ssh`, runs `ohai`, and caches the result locally.",
          "runner" => "`Fauxhai::Runner` — Runs Ohai on the current machine, sanitises the output, and prints JSON. Delegates to platform-specific mixins (`Runner::Default`, `Runner::Windows`).",
          "default" => "`Fauxhai::Runner::Default` — Mixin providing sanitised defaults for Linux/macOS/BSD platforms.",
          "windows" => "`Fauxhai::Runner::Windows` — Mixin providing sanitised defaults for Windows platforms.",
          "exception" => "`Fauxhai::Exception` — Custom error classes (`InvalidPlatform`, `InvalidVersion`).",
          "version" => "`Fauxhai::VERSION` — Gem version constant.",
        }

        source_files.each do |sf|
          key = sf.basename
          desc = descriptions[key] || "`#{sf.relative_path}`"
          lines << "- #{desc}"
        end

        lines << ""
        lines.join("\n")
      end

      def render_platform_summary(platforms)
        lines = []
        lines << "## Platform Data Summary"
        lines << ""
        lines << "| Platform | Versions | Count |"
        lines << "|----------|----------|-------|"

        platforms.each do |name, versions|
          lines << "| #{name} | #{versions.join(', ')} | #{versions.size} |"
        end

        lines << ""
        lines << "**Total platforms:** #{platforms.size}  "
        lines << "**Total version files:** #{platforms.values.sum(&:size)}"
        lines << ""
        lines.join("\n")
      end

      def render_data_flow
        <<~MD
          ## Data Flow

          ```mermaid
          sequenceDiagram
              participant User as Test / CLI
              participant Mocker as Fauxhai::Mocker
              participant FS as Local JSON
              participant GH as GitHub Raw
              participant Fetcher as Fauxhai::Fetcher
              participant SSH as Remote Host

              User->>Mocker: Fauxhai.mock(platform, version)
              Mocker->>FS: look up lib/fauxhai/platforms/<platform>/<version>.json
              alt file exists
                  FS-->>Mocker: JSON data
              else not found & github_fetching enabled
                  Mocker->>GH: HTTP GET raw JSON
                  GH-->>Mocker: JSON data
                  Mocker->>FS: cache locally
              end
              Mocker-->>User: parsed Hash

              User->>Fetcher: Fauxhai.fetch(host:, user:)
              Fetcher->>SSH: net/ssh exec "ohai"
              SSH-->>Fetcher: JSON output
              Fetcher->>FS: cache result
              Fetcher-->>User: parsed Hash
          ```
        MD
      end

      def render_generation_metadata
        <<~MD
          ## Generation Info

          - **Generated at:** #{Time.now.utc.strftime("%Y-%m-%d %H:%M:%S UTC")}
          - **Script:** `scripts/generate_architecture_diagram.rb`
          - **Refresh:** `rake architecture:generate`
        MD
      end

      private

      def node_id(sf)
        # Produce a valid Mermaid node ID from the file path
        sf.basename.split(/[^a-zA-Z0-9]/).map(&:capitalize).join
      end
    end
  end
end

# Run when executed directly
if __FILE__ == $PROGRAM_NAME
  output = ARGV[0] || Fauxhai::ArchitectureGenerator::DEFAULT_OUTPUT
  Fauxhai::ArchitectureGenerator.generate(output_path: output)
end
